[[repos]]
name = "chaos-mesh/website-zh"
sidecars = "sidebars.json"

[[repos.labels]]
label = "docs/cherry-version-2.0.1"
source_directory = "docs"
source_sidebars = "sidebars.js"
target_directory = "versioned_docs/version-2.0.1"
target_sidebars = "versioned_sidebars/version-2.0.1-sidebars.json"
