[[repos]]
name = "cwen0/docsbot"
sidecars = "sidebars.json"

[[repos.labels]]
label = "docs/cherry-version-2.0.0"
source_directory = "docs"
source_sidebars = "sidebars.js"
target_directory = "versioned_docs/version-2.0.0"
target_sidebars = "versioned_sidebars/version-2.0.0-sidebars.json"
