[[repos]]
name = "cwen0/docsbot"
sidecars = "sidebars.json"

[[repos.labels]]
label = "docs/cherry-version-2.0.0"
directory = "versioned_docs/version-2.0.0"
sidebars = "versioned_sidebars/version-2.0.0-sidebars.json"
